import { NavigationItem, Plan, Testimonial } from "./types";
export const APP_NAME = "KonnectSphere";
export const APP_DESCRIPTION =
  "Connect entrepreneurs with investors to fuel innovation and growth";
export const mainNavItems: NavigationItem[] = [
  {
    title: "Invest",
    href: "/invest",
    icon: "TrendingUp",
    submenu: [
      {
        title: "My Portfolio",
        href: "/investor/dashboard?tab=my-portfolio",
        icon: "Briefcase",
      },
      {
        title: "My Matches",
        href: "/investor/dashboard?tab=preferred-pitches",
        icon: "Target",
      },
      {
        title: "Explore Pitches",
        href: "/investor/dashboard?tab=explore-pitches",
        icon: "Search",
      },
      {
        title: "Search Pitches",
        href: "/explore-pitches",
        icon: "Filter",
      },
    ],
  },
  {
    title: "Fundraise",
    href: "/fundraise",
    icon: "DollarSign",
    submenu: [
      {
        title: "My Pitches",
        href: "/enterpreneur/dashboard?tab=my-pitches",
        icon: "FileText",
      },
      {
        title: "My Investors",
        href: "/enterpreneur/dashboard?tab=my-investors",
        icon: "MessageCircle",
      },
      {
        title: "Investor Search",
        href: "/search-investors",
        icon: "Search",
      },
      {
        title: "Add Pitch",
        href: "/add-pitch",
        icon: "Plus",
      },
    ],
  },

  {
    title: "Help Center",
    href: "/help",
    icon: "HelpCircle",
    submenu: [
      {
        title: "How it Works",
        href: "/how-it-works",
        icon: "PlayCircle",
      },
      {
        title: "Testimonials",
        href: "/testimonials",
        icon: "MessageSquare",
      },
      {
        title: "FAQs",
        href: "/faqs",
        icon: "HelpCircle",
      },
      {
        title: "Contact Us",
        href: "/contact",
        icon: "Mail",
      },
      {
        title: "Pricing",
        href: "/pricing",
        icon: "CreditCard",
      },
    ],
  },
  {
    title: "About Us",
    href: "/about",
    icon: "Info",
  },
];
export const stats = [
  { value: "$275K+", label: "Funding Raised" },
  { value: "100+", label: "Successful Matches" },
  { value: "85%", label: "Satisfaction Rate" },
  { value: "30+", label: "Active Investors" },
];

export const testimonials: Testimonial[] = [
  {
    id: 1,
    quote:
      "KonnectSphere helped me secure funding for my startup in just 8 weeks. The platform's investor matching algorithm is spot on!",
    name: "Sarah Johnson",
    title: "Founder & CEO",
    company: "EcoTech Solutions",
    avatar:
      "https://images.pexels.com/photos/762020/pexels-photo-762020.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 5,
    type: "entrepreneur",
  },
  {
    id: 2,
    quote:
      "As an investor, I've discovered incredible opportunities that perfectly match my investment criteria. The detailed pitch analytics save me hours of research.",
    name: "Michael Chang",
    title: "Angel Investor",
    company: "Horizon Ventures",
    avatar:
      "https://images.pexels.com/photos/1516680/pexels-photo-1516680.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 5,
    type: "investor",
  },
  {
    id: 3,
    quote:
      "The investor dashboard provides comprehensive analytics that help me make informed decisions about which startups to back.",
    name: "Lisa Rodriguez",
    title: "Investment Director",
    company: "Future Fund",
    avatar:
      "https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 4,
    type: "investor",
  },
  {
    id: 4,
    quote:
      "KonnectSphere's pitch creation tools helped me articulate my vision clearly, attracting the right investors for my MedTech startup.",
    name: "David Chen",
    title: "Founder",
    company: "NeuraTech",
    avatar:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 5,
    type: "entrepreneur",
  },
  {
    id: 5,
    quote:
      "The platform's communication tools streamlined our negotiations, making the funding process smooth and efficient.",
    name: "Olivia Martinez",
    title: "Co-founder",
    company: "Urban Gardens",
    avatar:
      "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=400",
    rating: 4,
    type: "entrepreneur",
  },
];
export const plans: Plan[] = [
  {
    name: "Basic",
    description: "Local Visibility. Essential Access.",
    price: {
      monthly: 49,
      yearly: 49,
    },
    features: [
      {
        text: "Pitch listed and visible only in your selected country",
        included: true,
      },
      { text: "Submit one business pitch", included: true },
      { text: "Standard customer support", included: true },
      { text: "Access to investor network within your region", included: true },
      { text: "Designed for local market exposure", included: true },
      { text: "Global visibility", included: false },
      { text: "Featured placement", included: false },
      { text: "Multiple pitch submissions", included: false },
      { text: "Priority support", included: false },
    ],
  },
  {
    name: "Premium",
    description: "Global Reach. Premium Benefits.",
    price: {
      monthly: 69,
      yearly: 69,
    },
    features: [
      { text: "Pitch listed and visible across all countries", included: true },
      { text: "Featured at the top of global search results", included: true },
      { text: "Upload supporting documents for investors", included: true },
      { text: "Submit up to 5 pitches", included: true },
      { text: "Priority customer support", included: true },
      { text: "Wider exposure to international investors", included: true },
      { text: "Higher chance of visibility and engagement", included: true },
    ],
    highlighted: true,
    badge: "Most Popular",
  },
];

export const investorPlan: Plan = {
  name: "Investor Access",
  description: "Discover High-Potential Ventures. Connect Globally.",
  price: {
    monthly: 0,
    yearly: 49,
  },
  features: [
    {
      text: "Browse and view business pitches from all countries",
      included: true,
    },
    {
      text: "Advanced search filters by industry, country, and funding stage",
      included: true,
    },
    {
      text: "Access to detailed pitch information and supporting documents",
      included: true,
    },
    {
      text: "Direct contact with entrepreneurs that match your investment interests",
      included: true,
    },
    {
      text: "Receive curated pitch recommendations based on your preferences",
      included: true,
    },
    {
      text: "Priority customer support for faster assistance and inquiries",
      included: true,
    },
    { text: "Save pitches to review or revisit anytime", included: true },
    {
      text: "Ideal for investors seeking quality deal flow and global opportunities",
      included: true,
    },
  ],
  highlighted: true,
  badge: "Annual Plan",
};

// Investment stages for companies/investors
export const INVESTMENT_STAGES = [
  "Achieving Sales",
  "Breaking Even",
  "MVP/Finished Product",
  "PreStartup/R&D",
  "Profitable",
  "Other",
];

// Industries list (matching across the platform)
export const INDUSTRIES_LIST = [
  "Agriculture",
  "Business Services",
  "Education & Training",
  "Energy & Natural Resources",
  "Entertainment & Leisure",
  "Fashion & Beauty",
  "Finance",
  "Food & Beverage",
  "Hospitality, Restaurants & Bars",
  "Manufacturing & Engineering",
  "Media",
  "Medical & Pharmaceutical",
  "Personal Services",
  "Products & Inventions",
  "Property & Land",
  "Retail",
  "Sales & Marketing",
  "Software & Web Development",
  "Technology",
  "Transport",
];

// Define the continent data structure
interface ContinentData {
  countries: string[];
}

// Complete list of continents and their countries (alphabetically sorted)
export const CONTINENTS: Record<string, ContinentData> = {
  "North America": {
    countries: [
      "Antigua and Barbuda",
      "Bahamas",
      "Barbados",
      "Belize",
      "Canada",
      "Costa Rica",
      "Cuba",
      "Dominica",
      "Dominican Republic",
      "El Salvador",
      "Grenada",
      "Guatemala",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Mexico",
      "Nicaragua",
      "Panama",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Trinidad and Tobago",
      "United States",
    ],
  },
  "South America": {
    countries: [
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "French Guiana",
      "Guyana",
      "Paraguay",
      "Peru",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
  Europe: {
    countries: [
      "Albania",
      "Andorra",
      "Austria",
      "Belgium",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "Ireland",
      "Italy",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "North Macedonia",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Ukraine",
      "United Kingdom",
      "Vatican City",
    ],
  },
  Asia: {
    countries: [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bahrain",
      "Bangladesh",
      "Bhutan",
      "Brunei",
      "Cambodia",
      "China",
      "Cyprus",
      "Georgia",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Israel",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Lebanon",
      "Malaysia",
      "Maldives",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "North Korea",
      "Oman",
      "Pakistan",
      "Palestine",
      "Philippines",
      "Qatar",
      "Russia",
      "Saudi Arabia",
      "Singapore",
      "South Korea",
      "Sri Lanka",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Thailand",
      "Timor-Leste",
      "Turkey",
      "Turkmenistan",
      "United Arab Emirates",
      "Uzbekistan",
      "Vietnam",
      "Yemen",
    ],
  },
  Africa: {
    countries: [
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cameroon",
      "Cape Verde",
      "Central African Republic",
      "Chad",
      "Comoros",
      "Democratic Republic of the Congo",
      "Djibouti",
      "Egypt",
      "Equatorial Guinea",
      "Eritrea",
      "Eswatini",
      "Ethiopia",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Ivory Coast",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libya",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Republic of the Congo",
      "Rwanda",
      "Sao Tome and Principe",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Tanzania",
      "Togo",
      "Tunisia",
      "Uganda",
      "Zambia",
      "Zimbabwe",
    ],
  },
  Oceania: {
    countries: [
      "Australia",
      "Fiji",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "New Zealand",
      "Palau",
      "Papua New Guinea",
      "Samoa",
      "Solomon Islands",
      "Tonga",
      "Tuvalu",
      "Vanuatu",
    ],
  },
};

// Flat list of all countries for backward compatibility
export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea, North",
  "Korea, South",
  "Kosovo",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];
// Industry interface
export interface Industry {
  name: string;
  iconName: string;
  description: string;
  color: string;
}

// Comprehensive industries list matching the provided image
export const INDUSTRIES: Industry[] = [
  {
    name: "Agriculture",
    iconName: "Wheat",
    description: "Farming, AgTech, Food Production, Supply Chain",
    color: "green",
  },
  {
    name: "Business Services",
    iconName: "Building2",
    description: "Consulting, Professional Services, B2B Solutions",
    color: "blue",
  },
  {
    name: "Education & Training",
    iconName: "GraduationCap",
    description: "EdTech, Learning Platforms, Training Solutions",
    color: "purple",
  },
  {
    name: "Energy & Natural Resources",
    iconName: "Zap",
    description: "Renewable Energy, Oil & Gas, Mining, Utilities",
    color: "yellow",
  },
  {
    name: "Entertainment & Leisure",
    iconName: "Gamepad2",
    description: "Gaming, Sports, Entertainment, Recreation",
    color: "pink",
  },
  {
    name: "Fashion & Beauty",
    iconName: "Shirt",
    description: "Fashion, Cosmetics, Beauty Products, Lifestyle",
    color: "rose",
  },
  {
    name: "Finance",
    iconName: "BadgeDollarSign",
    description: "Fintech, Banking, Insurance, Investment Services",
    color: "emerald",
  },
  {
    name: "Food & Beverage",
    iconName: "UtensilsCrossed",
    description: "Food Production, Beverages, Restaurants, Catering",
    color: "orange",
  },
  {
    name: "Hospitality, Restaurants & Bars",
    iconName: "Coffee",
    description: "Hotels, Travel, Dining, Event Management",
    color: "amber",
  },
  {
    name: "Manufacturing & Engineering",
    iconName: "Cog",
    description: "Industrial Manufacturing, Engineering Services",
    color: "gray",
  },
  {
    name: "Media",
    iconName: "Camera",
    description: "Digital Media, Broadcasting, Content Creation",
    color: "violet",
  },
  {
    name: "Medical & Pharmaceutical",
    iconName: "HeartPulse",
    description: "Healthcare, Medical Devices, Pharmaceuticals",
    color: "red",
  },
  {
    name: "Personal Services",
    iconName: "Scissors",
    description: "Personal Care, Wellness, Beauty Services",
    color: "indigo",
  },
  {
    name: "Products & Inventions",
    iconName: "Package",
    description: "Product Development, Innovation, R&D",
    color: "cyan",
  },
  {
    name: "Property & Land",
    iconName: "Home",
    description: "Real Estate, PropTech, Construction, Development",
    color: "stone",
  },
  {
    name: "Retail",
    iconName: "ShoppingBag",
    description: "E-commerce, Retail Technology, Consumer Goods",
    color: "blue",
  },
  {
    name: "Sales & Marketing",
    iconName: "TrendingUp",
    description: "MarTech, Advertising, Sales Tools, Analytics",
    color: "green",
  },
  {
    name: "Software & Web Development",
    iconName: "Code2",
    description: "SaaS, Web Development, Software Solutions",
    color: "blue",
  },
  {
    name: "Technology",
    iconName: "Laptop",
    description: "Hardware, AI, Blockchain, IoT, Cloud Computing",
    color: "slate",
  },
  {
    name: "Transport",
    iconName: "Truck",
    description: "Logistics, Transportation, Mobility Solutions",
    color: "zinc",
  },
];
